name: deploy de la pagina
on:
  push:
    - main
jobs:
  deploy-page:
    runs-on: ubuntu.latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Deploy
        uses: JamesIves/github-page-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to
          folder: . #The folder the action should deploy
          